# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: TSAArchives.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)


import TSKArchives_pb2
import TSPMessages_pb2
import TSWPArchives_pb2
import TSSArchives_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='TSAArchives.proto',
  package='TSA',
  serialized_pb='\n\x11TSAArchives.proto\x12\x03TSA\x1a\x11TSKArchives.proto\x1a\x11TSPMessages.proto\x1a\x12TSWPArchives.proto\x1a\x11TSSArchives.proto\"\x93\x03\n\x0f\x44ocumentArchive\x12#\n\x05super\x18\x01 \x02(\x0b\x32\x14.TSK.DocumentArchive\x12\x45\n\x19text_preset_display_items\x18\x02 \x03(\x0b\x32\".TSWP.TextPresetDisplayItemArchive\x12\x19\n\x11\x63reation_language\x18\x03 \x01(\t\x12*\n\x12\x63\x61lculation_engine\x18\x04 \x01(\x0b\x32\x0e.TSP.Reference\x12\"\n\nview_state\x18\x05 \x01(\x0b\x32\x0e.TSP.Reference\x12.\n\x16\x66unction_browser_state\x18\x06 \x01(\x0b\x32\x0e.TSP.Reference\x12\x31\n\x19tables_custom_format_list\x18\x07 \x01(\x0b\x32\x0e.TSP.Reference\x12)\n!needs_movie_compatibility_upgrade\x18\x08 \x01(\x08\x12\x1b\n\x13template_identifier\x18\t \x01(\t\"\x84\x01\n\x1b\x46unctionBrowserStateArchive\x12\x18\n\x10recent_functions\x18\x01 \x03(\r\x12\x16\n\x0e\x62\x61\x63k_functions\x18\x02 \x03(\r\x12\x19\n\x11\x66orward_functions\x18\x03 \x03(\r\x12\x18\n\x10\x63urrent_function\x18\x04 \x01(\r\"I\n\x13TestDocumentArchive\x12#\n\x05super\x18\x01 \x02(\x0b\x32\x14.TSA.DocumentArchive\x12\r\n\x05value\x18\x02 \x01(\t\"C\n\x1dPropagatePresetCommandArchive\x12\"\n\x05super\x18\x01 \x02(\x0b\x32\x13.TSK.CommandArchive')




_DOCUMENTARCHIVE = _descriptor.Descriptor(
  name='DocumentArchive',
  full_name='TSA.DocumentArchive',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='super', full_name='TSA.DocumentArchive.super', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='text_preset_display_items', full_name='TSA.DocumentArchive.text_preset_display_items', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='creation_language', full_name='TSA.DocumentArchive.creation_language', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='calculation_engine', full_name='TSA.DocumentArchive.calculation_engine', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='view_state', full_name='TSA.DocumentArchive.view_state', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='function_browser_state', full_name='TSA.DocumentArchive.function_browser_state', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='tables_custom_format_list', full_name='TSA.DocumentArchive.tables_custom_format_list', index=6,
      number=7, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='needs_movie_compatibility_upgrade', full_name='TSA.DocumentArchive.needs_movie_compatibility_upgrade', index=7,
      number=8, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='template_identifier', full_name='TSA.DocumentArchive.template_identifier', index=8,
      number=9, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=104,
  serialized_end=507,
)


_FUNCTIONBROWSERSTATEARCHIVE = _descriptor.Descriptor(
  name='FunctionBrowserStateArchive',
  full_name='TSA.FunctionBrowserStateArchive',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='recent_functions', full_name='TSA.FunctionBrowserStateArchive.recent_functions', index=0,
      number=1, type=13, cpp_type=3, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='back_functions', full_name='TSA.FunctionBrowserStateArchive.back_functions', index=1,
      number=2, type=13, cpp_type=3, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='forward_functions', full_name='TSA.FunctionBrowserStateArchive.forward_functions', index=2,
      number=3, type=13, cpp_type=3, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='current_function', full_name='TSA.FunctionBrowserStateArchive.current_function', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=510,
  serialized_end=642,
)


_TESTDOCUMENTARCHIVE = _descriptor.Descriptor(
  name='TestDocumentArchive',
  full_name='TSA.TestDocumentArchive',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='super', full_name='TSA.TestDocumentArchive.super', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='value', full_name='TSA.TestDocumentArchive.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=644,
  serialized_end=717,
)


_PROPAGATEPRESETCOMMANDARCHIVE = _descriptor.Descriptor(
  name='PropagatePresetCommandArchive',
  full_name='TSA.PropagatePresetCommandArchive',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='super', full_name='TSA.PropagatePresetCommandArchive.super', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=719,
  serialized_end=786,
)

_DOCUMENTARCHIVE.fields_by_name['super'].message_type = TSKArchives_pb2._DOCUMENTARCHIVE
_DOCUMENTARCHIVE.fields_by_name['text_preset_display_items'].message_type = TSWPArchives_pb2._TEXTPRESETDISPLAYITEMARCHIVE
_DOCUMENTARCHIVE.fields_by_name['calculation_engine'].message_type = TSPMessages_pb2._REFERENCE
_DOCUMENTARCHIVE.fields_by_name['view_state'].message_type = TSPMessages_pb2._REFERENCE
_DOCUMENTARCHIVE.fields_by_name['function_browser_state'].message_type = TSPMessages_pb2._REFERENCE
_DOCUMENTARCHIVE.fields_by_name['tables_custom_format_list'].message_type = TSPMessages_pb2._REFERENCE
_TESTDOCUMENTARCHIVE.fields_by_name['super'].message_type = _DOCUMENTARCHIVE
_PROPAGATEPRESETCOMMANDARCHIVE.fields_by_name['super'].message_type = TSKArchives_pb2._COMMANDARCHIVE
DESCRIPTOR.message_types_by_name['DocumentArchive'] = _DOCUMENTARCHIVE
DESCRIPTOR.message_types_by_name['FunctionBrowserStateArchive'] = _FUNCTIONBROWSERSTATEARCHIVE
DESCRIPTOR.message_types_by_name['TestDocumentArchive'] = _TESTDOCUMENTARCHIVE
DESCRIPTOR.message_types_by_name['PropagatePresetCommandArchive'] = _PROPAGATEPRESETCOMMANDARCHIVE

class DocumentArchive(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _DOCUMENTARCHIVE

  # @@protoc_insertion_point(class_scope:TSA.DocumentArchive)

class FunctionBrowserStateArchive(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _FUNCTIONBROWSERSTATEARCHIVE

  # @@protoc_insertion_point(class_scope:TSA.FunctionBrowserStateArchive)

class TestDocumentArchive(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _TESTDOCUMENTARCHIVE

  # @@protoc_insertion_point(class_scope:TSA.TestDocumentArchive)

class PropagatePresetCommandArchive(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _PROPAGATEPRESETCOMMANDARCHIVE

  # @@protoc_insertion_point(class_scope:TSA.PropagatePresetCommandArchive)


# @@protoc_insertion_point(module_scope)
