class Common(object):
  TSK_DocumentArchive= 200
  TSK_CommandHistory= 201
  TSK_CommandGroupArchive= 202
  TSK_CommandContainerArchive= 203
  TSK_ReplaceAllCommandArchive= 204
  TSK_TreeNode= 205
  TSK_ProgressiveCommandGroupArchive= 206
  TSK_CommandSelectionBehaviorHistoryArchive= 208
  TSK_UndoRedoStateCommandSelectionBehaviorArchive= 209
  TSK_ViewStateArchive= 210
  TSK_DocumentSupportArchive= 211
  TSK_AnnotationAuthorArchive= 212
  TSK_AnnotationAuthorStorageArchive= 213
  TSK_AddAnnotationAuthorCommandArchive= 214
  TSK_SetAnnotationAuthorColorCommandArchive= 215
  TSS_StyleArchive= 400
  TSS_StylesheetArchive= 401
  TSS_ThemeArchive= 402
  TSS_ApplyThemeCommandArchive= 410
  TSS_ApplyThemeChildCommandArchive= 411
  TSS_StyleUpdatePropertyMapCommandArchive= 412
  TSS_ThemeReplacePresetCommandArchive= 413
  TSS_ThemeAddStylePresetCommandArchive= 414
  TSS_ThemeRemoveStylePresetCommandArchive= 415
  TSS_ThemeReplaceColorPresetCommandArchive= 416
  TSS_ThemeMovePresetCommandArchive= 417
  TSS_ThemeReplaceStylePresetCommandArchive= 418
  TSA_DocumentArchive= 600
  TSA_FunctionBrowserStateArchive= 601
  TSA_PropagatePresetCommandArchive= 602
  TSWP_StorageArchive= 2001
  TSWP_SelectionArchive= 2002
  TSWP_DrawableAttachmentArchive= 2003
  TSWP_TextualAttachmentArchive= 2004
  TSWP_StorageArchive= 2005
  TSWP_UIGraphicalAttachment= 2006
  TSWP_TextualAttachmentArchive= 2007
  TSWP_FootnoteReferenceAttachmentArchive= 2008
  TSWP_TextualAttachmentArchive= 2009
  TSWP_TSWPTOCPageNumberAttachmentArchive= 2010
  TSWP_ShapeInfoArchive= 2011
  TSWP_HighlightArchive= 2013
  TSWP_CommentInfoArchive= 2014
  TSWP_CharacterStyleArchive= 2021
  TSWP_ParagraphStyleArchive= 2022
  TSWP_ListStyleArchive= 2023
  TSWP_ColumnStyleArchive= 2024
  TSWP_ShapeStyleArchive= 2025
  TSWP_TOCEntryStyleArchive= 2026
  TSWP_PlaceholderSmartFieldArchive= 2031
  TSWP_HyperlinkFieldArchive= 2032
  TSWP_FilenameSmartFieldArchive= 2033
  TSWP_DateTimeSmartFieldArchive= 2034
  TSWP_BookmarkFieldArchive= 2035
  TSWP_MergeSmartFieldArchive= 2036
  TSWP_CitationRecordArchive= 2037
  TSWP_CitationSmartFieldArchive= 2038
  TSWP_UnsupportedHyperlinkFieldArchive= 2039
  TSWP_BibliographySmartFieldArchive= 2040
  TSWP_TOCSmartFieldArchive= 2041
  TSWP_RubyFieldArchive= 2042
  TSWP_NumberAttachmentArchive= 2043
  TSWP_TextStylePresetArchive= 2050
  TSWP_TOCSettingsArchive= 2051
  TSWP_TOCEntryInstanceArchive= 2052
  TSWP_ChangeArchive= 2060
  TSK_DeprecatedChangeAuthorArchive= 2061
  TSWP_ChangeSessionArchive= 2062
  TSWP_TextCommandArchive= 2101
  TSWP_InsertAttachmentCommandArchive= 2102
  TSWP_ReplaceAllTextCommandArchive= 2104
  TSWP_FormatTextCommandArchive= 2105
  TSWP_ApplyPlaceholderTextCommandArchive= 2107
  TSWP_ApplyHighlightTextCommandArchive= 2108
  TSWP_CreateHyperlinkCommandArchive= 2113
  TSWP_RemoveHyperlinkCommandArchive= 2114
  TSWP_ModifyHyperlinkCommandArchive= 2115
  TSWP_ApplyRubyTextCommandArchive= 2116
  TSWP_RemoveRubyTextCommandArchive= 2117
  TSWP_ModifyRubyTextCommandArchive= 2118
  TSWP_UpdateDateTimeFieldCommandArchive= 2119
  TSWP_ModifyTOCSettingsBaseCommandArchive= 2120
  TSWP_ModifyTOCSettingsForTOCInfoCommandArchive= 2121
  TSWP_ModifyTOCSettingsPresetForThemeCommandArchive= 2122
  TSWP_AnchorAttachmentCommandArchive= 2206
  TSWP_TextApplyThemeCommandArchive= 2207
  TSWP_ShapeApplyPresetCommandArchive= 2231
  TSWP_ShapePasteStyleCommandArchive= 2232
  TSWP_TOCInfoArchive= 2240
  TSWP_TOCAttachmentArchive= 2241
  TSWP_TOCLayoutHintArchive= 2242
  TSWP_StyleBaseCommandArchive= 2400
  TSWP_StyleCreateCommandArchive= 2401
  TSWP_StyleRenameCommandArchive= 2402
  TSWP_StyleUpdateCommandArchive= 2403
  TSWP_StyleDeleteCommandArchive= 2404
  TSWP_StyleReorderCommandArchive= 2405
  TSWP_StyleUpdatePropertyMapCommandArchive= 2406
  TSD_DrawableArchive= 3002
  TSD_ContainerArchive= 3003
  TSD_ShapeArchive= 3004
  TSD_ImageArchive= 3005
  TSD_MaskArchive= 3006
  TSD_MovieArchive= 3007
  TSD_GroupArchive= 3008
  TSD_ConnectionLineArchive= 3009
  TSD_ShapeStyleArchive= 3015
  TSD_MediaStyleArchive= 3016
  TSD_DrawablesCommandGroupArchive= 3020
  TSD_InfoGeometryCommandArchive= 3021
  TSD_DrawablePathSourceCommandArchive= 3022
  TSD_ShapePathSourceFlipCommandArchive= 3023
  TSD_ImageMaskCommandArchive= 3024
  TSD_ImageMediaCommandArchive= 3025
  TSD_ImageReplaceCommandArchive= 3026
  TSD_MediaOriginalSizeCommandArchive= 3027
  TSD_ShapeStyleSetValueCommandArchive= 3028
  TSD_MediaStyleSetValueCommandArchive= 3030
  TSD_ShapeApplyPresetCommandArchive= 3031
  TSD_MediaApplyPresetCommandArchive= 3032
  TSD_DrawableApplyThemeCommandArchive= 3033
  TSD_MovieSetValueCommandArchive= 3034
  TSD_ShapeSetLineEndCommandArchive= 3035
  TSD_ExteriorTextWrapCommandArchive= 3036
  TSD_MediaFlagsCommandArchive= 3037
  TSD_GroupDrawablesCommandArchive= 3038
  TSD_UngroupGroupCommandArchive= 3039
  TSD_DrawableHyperlinkCommandArchive= 3040
  TSD_ConnectionLineConnectCommandArchive= 3041
  TSD_InstantAlphaCommandArchive= 3042
  TSD_DrawableLockCommandArchive= 3043
  TSD_CanvasSelectionArchive= 3045
  TSD_CommandSelectionBehaviorArchive= 3046
  TSD_GuideStorageArchive= 3047
  TSD_StyledInfoSetStyleCommandArchive= 3048
  TSD_DrawableInfoCommentCommandArchive= 3049
  TSD_GuideCommandArchive= 3050
  TSD_DrawableAspectRatioLockedCommandArchive= 3051
  TSD_ContainerRemoveChildrenCommandArchive= 3052
  TSD_ContainerInsertChildrenCommandArchive= 3053
  TSD_ContainerReorderChildrenCommandArchive= 3054
  TSD_ImageAdjustmentsCommandArchive= 3055
  TSD_CommentStorageArchive= 3056
  TSD_ThemeReplaceFillPresetCommandArchive= 3057
  TSD_DrawableAccessibilityDescriptionCommandArchive= 3058
  TSD_PasteStyleCommandArchive= 3059
  TSD_CommentStorageApplyCommandArchive= 3060
  TSCE_CalculationEngineArchive= 4000
  TSCE_FormulaRewriteCommandArchive= 4001
  TSCE_TrackedReferencesRewriteCommandArchive= 4002
  TSCE_NamedReferenceManagerArchive= 4003
  TSCE_ReferenceTrackerArchive= 4004
  TSCE_TrackedReferenceArchive= 4005
  TSCH_PreUFF_ChartInfoArchive= 5000
  TSCH_PreUFF_ChartGridArchive= 5002
  TSCH_ChartMediatorArchive= 5004
  TSCH_PreUFF_ChartStyleArchive= 5010
  TSCH_PreUFF_ChartSeriesStyleArchive= 5011
  TSCH_PreUFF_ChartAxisStyleArchive= 5012
  TSCH_PreUFF_LegendStyleArchive= 5013
  TSCH_PreUFF_ChartNonStyleArchive= 5014
  TSCH_PreUFF_ChartSeriesNonStyleArchive= 5015
  TSCH_PreUFF_ChartAxisNonStyleArchive= 5016
  TSCH_PreUFF_LegendNonStyleArchive= 5017
  TSCH_ChartStylePreset= 5020
  TSCH_ChartDrawableArchive= 5021
  TSCH_ChartStyleArchive= 5022
  TSCH_ChartNonStyleArchive= 5023
  TSCH_LegendStyleArchive= 5024
  TSCH_LegendNonStyleArchive= 5025
  TSCH_ChartAxisStyleArchive= 5026
  TSCH_ChartAxisNonStyleArchive= 5027
  TSCH_ChartSeriesStyleArchive= 5028
  TSCH_ChartSeriesNonStyleArchive= 5029
  TSCH_CommandSetChartTypeArchive= 5103
  TSCH_CommandSetSeriesNameArchive= 5104
  TSCH_CommandSetCategoryNameArchive= 5105
  TSCH_CommandSetScatterFormatArchive= 5107
  TSCH_CommandSetLegendFrameArchive= 5108
  TSCH_CommandSetGridValueArchive= 5109
  TSCH_CommandSetGridDirectionArchive= 5110
  TSCH_SynchronousCommandArchive= 5113
  TSCH_CommandReplaceAllArchive= 5114
  TSCH_CommandAddGridRowsArchive= 5115
  TSCH_CommandAddGridColumnsArchive= 5116
  TSCH_CommandSetPreviewLocArchive= 5117
  TSCH_CommandMoveGridRowsArchive= 5118
  TSCH_CommandMoveGridColumnsArchive= 5119
  TSCH_CommandDeleteGridRowsArchive= 5120
  TSCH_CommandDeleteGridColumnsArchive= 5121
  TSCH_CommandSetPieWedgeExplosion= 5122
  TSCH_CommandStyleSwapArchive= 5123
  TSCH_CommandChartApplyTheme= 5124
  TSCH_CommandChartApplyPreset= 5125
  TSCH_ChartCommandArchive= 5126
  TSCH_CommandReplaceGridValuesArchive= 5127
  TSCH_StylePasteboardDataArchive= 5129
  TSCH_CommandSetMultiDataSetIndexArchive= 5130
  TSCH_CommandReplaceThemePresetArchive= 5131
  TSCH_CommandInvalidateWPCaches= 5132
  TST_TableInfoArchive= 6000
  TST_TableModelArchive= 6001
  TST_Tile= 6002
  TST_TableStyleArchive= 6003
  TST_CellStyleArchive= 6004
  TST_TableDataList= 6005
  TST_HeaderStorageBucket= 6006
  TST_WPTableInfoArchive= 6007
  TST_TableStylePresetArchive= 6008
  TST_TableStrokePresetArchive= 6009
  TST_ConditionalStyleSetArchive= 6010
  TST_TableCommandArchive= 6100
  TST_CommandDeleteCellsArchive= 6101
  TST_CommandInsertColumnsOrRowsArchive= 6102
  TST_CommandRemoveColumnsOrRowsArchive= 6103
  TST_CommandResizeColumnOrRowArchive= 6104
  TST_CommandSetCellArchive= 6105
  TST_CommandSetNumberOfHeadersOrFootersArchive= 6106
  TST_CommandSetTableNameArchive= 6107
  TST_CommandStyleCellsArchive= 6108
  TST_CommandFillCellsArchive= 6109
  TST_CommandReplaceAllTextArchive= 6110
  TST_CommandChangeFreezeHeaderStateArchive= 6111
  TST_CommandReplaceTextArchive= 6112
  TST_CommandPasteArchive= 6113
  TST_CommandSetTableNameEnabledArchive= 6114
  TST_CommandMoveRowsArchive= 6115
  TST_CommandMoveColumnsArchive= 6116
  TST_CommandApplyTableStylePresetArchive= 6117
  TST_CommandApplyStrokePresetArchive= 6118
  TST_CommandSetExplicitFormatArchive= 6119
  TST_CommandSetRepeatingHeaderEnabledArchive= 6120
  TST_CommandApplyThemeToTableArchive= 6121
  TST_CommandApplyThemeChildForTableArchive= 6122
  TST_CommandSortArchive= 6123
  TST_CommandToggleTextPropertyArchive= 6124
  TST_CommandStyleTableArchive= 6125
  TST_CommandSetNumberOfDecimalPlacesArchive= 6126
  TST_CommandSetShowThousandsSeparatorArchive= 6127
  TST_CommandSetNegativeNumberStyleArchive= 6128
  TST_CommandSetFractionAccuracyArchive= 6129
  TST_CommandSetSingleNumberFormatParameterArchive= 6130
  TST_CommandSetCurrencyCodeArchive= 6131
  TST_CommandSetUseAccountingStyleArchive= 6132
  TST_CommandRewriteFormulasForSortArchive= 6134
  TST_CommandRewriteFormulasForTectonicShiftArchive= 6135
  TST_CommandSetTableFontNameArchive= 6136
  TST_CommandSetTableFontSizeArchive= 6137
  TST_CommandRewriteFormulasForMoveArchive= 6138
  TST_CommandFixStylesInHeadersOrFootersArchive= 6139
  TST_CommandResetFillPropertyToDefault= 6141
  TST_CommandSetTableNameHeightArchive= 6142
  TST_CommandMergeUnmergeArchive= 6143
  TST_MergeRegionMapArchive= 6144
  TST_CommandHideShowArchive= 6145
  TST_CommandSetBaseArchive= 6146
  TST_CommandSetBasePlacesArchive= 6147
  TST_CommandSetBaseUseMinusSignArchive= 6148
  TST_FormulaEqualsTokenAttachmentArchive= 6179
  TST_TokenAttachmentArchive= 6181
  TST_ExpressionNodeArchive= 6182
  TST_BooleanNodeArchive= 6183
  TST_NumberNodeArchive= 6184
  TST_StringNodeArchive= 6185
  TST_ArrayNodeArchive= 6186
  TST_ListNodeArchive= 6187
  TST_OperatorNodeArchive= 6188
  TST_FunctionNodeArchive= 6189
  TST_DateNodeArchive= 6190
  TST_ReferenceNodeArchive= 6191
  TST_DurationNodeArchive= 6192
  TST_ArgumentPlaceholderNodeArchive= 6193
  TST_PostfixOperatorNodeArchive= 6194
  TST_PrefixOperatorNodeArchive= 6195
  TST_FunctionEndNodeArchive= 6196
  TST_EmptyExpressionNodeArchive= 6197
  TST_LayoutHintArchive= 6198
  TST_CompletionTokenAttachmentArchive= 6199
  TST_FormulaEditingCommandGroupArchive= 6200
  TST_TableDataList= 6201
  TST_CommandCoerceMultipleCellsArchive= 6202
  TST_CommandSetMultipleCellsCustomArchive= 6203
  TST_HiddenStateFormulaOwnerArchive= 6204
  TST_CommandSetAutomaticDurationUnitsArchive= 6205
  TST_PopUpMenuModel= 6206
  TST_CommandSetControlMinimumArchive= 6207
  TST_CommandSetControlMaximumArchive= 6208
  TST_CommandSetControlIncrementArchive= 6209
  TST_CommandSetControlCellsDisplayNumberFormatArchive= 6210
  TST_CommandSetMultipleCellsMultipleChoiceListArchive= 6211
  TST_CommandSetMultipleChoiceListFormatForEditedItemArchive= 6212
  TST_CommandSetMultipleChoiceListFormatForDeleteItemArchive= 6213
  TST_CommandSetMultipleChoiceListFormatForReorderItemArchive= 6214
  TST_CommandSetMultipleChoiceListFormatForInitialValueArchive= 6215
  TST_CommandRewriteFormulasForCellMergeArchive= 6216
  TST_TableInfoGeometryCommandArchive= 6217
  TST_RichTextPayloadArchive= 6218
  TST_EditingStateArchive= 6219
  TST_FilterSetArchive= 6220
  TST_CommandSetFiltersEnabledArchive= 6221
  TST_CommandRewriteFilterFormulasForTectonicShiftArchive= 6222
  TST_CommandRewriteFilterFormulasForSortArchive= 6223
  TST_CommandRewriteFilterFormulasForTableResizeArchive= 6224
  TST_CommandSetAutomaticFormatArchive= 6225
  TST_CommandTextPreflightInsertCellArchive= 6226
  TST_FormulaEditingCommandSelectionBehaviorArchive= 6227
  TST_CommandDeleteCellContentsArchive= 6228
  TST_CommandPostflightSetCellArchive= 6229
  TST_CommandRewriteConditionalStylesForTectonicShiftArchive= 6231
  TST_CommandRewriteConditionalStylesForSortArchive= 6232
  TST_CommandRewriteConditionalStylesForRangeMoveArchive= 6233
  TST_CommandRewriteConditionalStylesForCellMergeArchive= 6234
  TST_IdentifierNodeArchive= 6235
  TST_UndoRedoStateCommandSelectionBehaviorArchive= 6236
  TST_CommandSetStyleApplyClearsAllFlagArchive= 6237
  TST_CommandSetDateTimeFormatArchive= 6238
  TST_TableCommandSelectionBehaviorArchive= 6239
  TST_CommandAddQuickFilterRulesArchive= 6240
  TST_CommandModifyFilterRuleArchive= 6241
  TST_CommandDeleteFilterRulesArchive= 6242
  TST_CommandApplyCellCommentArchive= 6244
  TST_CommandApplyConditionalStyleSetArchive= 6245
  TST_CommandSetFormulaTokenizationArchive= 6246
  TST_TableStyleNetworkArchive= 6247
  TST_CommandSetFilterEnabledArchive= 6248
  TST_CommandSetFilterRuleEnabledArchive= 6249
  TST_CommandSetFilterSetTypeArchive= 6250
  TST_CommandSetStyleNetworkArchive= 6251
  TST_CommandMutateCellsArchive= 6252
  TST_DisableTableNameSelectionBehaviorArchive= 6253
  TST_CommandDisableFilterRulesForColumnArchive= 6254
  TST_CommandSetTextStyleArchive= 6255
  TST_CommandNotifyForTransformingArchive= 6256
  TSP_PasteboardObject= 11000
  TSP_PackageMetadata= 11006
  TSP_PasteboardMetadata= 11007
  TSP_ObjectContainer= 11008


  DICTIONARY = {
    200: "TSK_DocumentArchive",
    201: "TSK_CommandHistory",
    202: "TSK_CommandGroupArchive",
    203: "TSK_CommandContainerArchive",
    204: "TSK_ReplaceAllCommandArchive",
    205: "TSK_TreeNode",
    206: "TSK_ProgressiveCommandGroupArchive",
    208: "TSK_CommandSelectionBehaviorHistoryArchive",
    209: "TSK_UndoRedoStateCommandSelectionBehaviorArchive",
    210: "TSK_ViewStateArchive",
    211: "TSK_DocumentSupportArchive",
    212: "TSK_AnnotationAuthorArchive",
    213: "TSK_AnnotationAuthorStorageArchive",
    214: "TSK_AddAnnotationAuthorCommandArchive",
    215: "TSK_SetAnnotationAuthorColorCommandArchive",
    400: "TSS_StyleArchive",
    401: "TSS_StylesheetArchive",
    402: "TSS_ThemeArchive",
    410: "TSS_ApplyThemeCommandArchive",
    411: "TSS_ApplyThemeChildCommandArchive",
    412: "TSS_StyleUpdatePropertyMapCommandArchive",
    413: "TSS_ThemeReplacePresetCommandArchive",
    414: "TSS_ThemeAddStylePresetCommandArchive",
    415: "TSS_ThemeRemoveStylePresetCommandArchive",
    416: "TSS_ThemeReplaceColorPresetCommandArchive",
    417: "TSS_ThemeMovePresetCommandArchive",
    418: "TSS_ThemeReplaceStylePresetCommandArchive",
    600: "TSA_DocumentArchive",
    601: "TSA_FunctionBrowserStateArchive",
    602: "TSA_PropagatePresetCommandArchive",
    2001: "TSWP_StorageArchive",
    2002: "TSWP_SelectionArchive",
    2003: "TSWP_DrawableAttachmentArchive",
    2004: "TSWP_TextualAttachmentArchive",
    2005: "TSWP_StorageArchive",
    2006: "TSWP_UIGraphicalAttachment",
    2007: "TSWP_TextualAttachmentArchive",
    2008: "TSWP_FootnoteReferenceAttachmentArchive",
    2009: "TSWP_TextualAttachmentArchive",
    2010: "TSWP_TSWPTOCPageNumberAttachmentArchive",
    2011: "TSWP_ShapeInfoArchive",
    2013: "TSWP_HighlightArchive",
    2014: "TSWP_CommentInfoArchive",
    2021: "TSWP_CharacterStyleArchive",
    2022: "TSWP_ParagraphStyleArchive",
    2023: "TSWP_ListStyleArchive",
    2024: "TSWP_ColumnStyleArchive",
    2025: "TSWP_ShapeStyleArchive",
    2026: "TSWP_TOCEntryStyleArchive",
    2031: "TSWP_PlaceholderSmartFieldArchive",
    2032: "TSWP_HyperlinkFieldArchive",
    2033: "TSWP_FilenameSmartFieldArchive",
    2034: "TSWP_DateTimeSmartFieldArchive",
    2035: "TSWP_BookmarkFieldArchive",
    2036: "TSWP_MergeSmartFieldArchive",
    2037: "TSWP_CitationRecordArchive",
    2038: "TSWP_CitationSmartFieldArchive",
    2039: "TSWP_UnsupportedHyperlinkFieldArchive",
    2040: "TSWP_BibliographySmartFieldArchive",
    2041: "TSWP_TOCSmartFieldArchive",
    2042: "TSWP_RubyFieldArchive",
    2043: "TSWP_NumberAttachmentArchive",
    2050: "TSWP_TextStylePresetArchive",
    2051: "TSWP_TOCSettingsArchive",
    2052: "TSWP_TOCEntryInstanceArchive",
    2060: "TSWP_ChangeArchive",
    2061: "TSK_DeprecatedChangeAuthorArchive",
    2062: "TSWP_ChangeSessionArchive",
    2101: "TSWP_TextCommandArchive",
    2102: "TSWP_InsertAttachmentCommandArchive",
    2104: "TSWP_ReplaceAllTextCommandArchive",
    2105: "TSWP_FormatTextCommandArchive",
    2107: "TSWP_ApplyPlaceholderTextCommandArchive",
    2108: "TSWP_ApplyHighlightTextCommandArchive",
    2113: "TSWP_CreateHyperlinkCommandArchive",
    2114: "TSWP_RemoveHyperlinkCommandArchive",
    2115: "TSWP_ModifyHyperlinkCommandArchive",
    2116: "TSWP_ApplyRubyTextCommandArchive",
    2117: "TSWP_RemoveRubyTextCommandArchive",
    2118: "TSWP_ModifyRubyTextCommandArchive",
    2119: "TSWP_UpdateDateTimeFieldCommandArchive",
    2120: "TSWP_ModifyTOCSettingsBaseCommandArchive",
    2121: "TSWP_ModifyTOCSettingsForTOCInfoCommandArchive",
    2122: "TSWP_ModifyTOCSettingsPresetForThemeCommandArchive",
    2206: "TSWP_AnchorAttachmentCommandArchive",
    2207: "TSWP_TextApplyThemeCommandArchive",
    2231: "TSWP_ShapeApplyPresetCommandArchive",
    2232: "TSWP_ShapePasteStyleCommandArchive",
    2240: "TSWP_TOCInfoArchive",
    2241: "TSWP_TOCAttachmentArchive",
    2242: "TSWP_TOCLayoutHintArchive",
    2400: "TSWP_StyleBaseCommandArchive",
    2401: "TSWP_StyleCreateCommandArchive",
    2402: "TSWP_StyleRenameCommandArchive",
    2403: "TSWP_StyleUpdateCommandArchive",
    2404: "TSWP_StyleDeleteCommandArchive",
    2405: "TSWP_StyleReorderCommandArchive",
    2406: "TSWP_StyleUpdatePropertyMapCommandArchive",
    3002: "TSD_DrawableArchive",
    3003: "TSD_ContainerArchive",
    3004: "TSD_ShapeArchive",
    3005: "TSD_ImageArchive",
    3006: "TSD_MaskArchive",
    3007: "TSD_MovieArchive",
    3008: "TSD_GroupArchive",
    3009: "TSD_ConnectionLineArchive",
    3015: "TSD_ShapeStyleArchive",
    3016: "TSD_MediaStyleArchive",
    3020: "TSD_DrawablesCommandGroupArchive",
    3021: "TSD_InfoGeometryCommandArchive",
    3022: "TSD_DrawablePathSourceCommandArchive",
    3023: "TSD_ShapePathSourceFlipCommandArchive",
    3024: "TSD_ImageMaskCommandArchive",
    3025: "TSD_ImageMediaCommandArchive",
    3026: "TSD_ImageReplaceCommandArchive",
    3027: "TSD_MediaOriginalSizeCommandArchive",
    3028: "TSD_ShapeStyleSetValueCommandArchive",
    3030: "TSD_MediaStyleSetValueCommandArchive",
    3031: "TSD_ShapeApplyPresetCommandArchive",
    3032: "TSD_MediaApplyPresetCommandArchive",
    3033: "TSD_DrawableApplyThemeCommandArchive",
    3034: "TSD_MovieSetValueCommandArchive",
    3035: "TSD_ShapeSetLineEndCommandArchive",
    3036: "TSD_ExteriorTextWrapCommandArchive",
    3037: "TSD_MediaFlagsCommandArchive",
    3038: "TSD_GroupDrawablesCommandArchive",
    3039: "TSD_UngroupGroupCommandArchive",
    3040: "TSD_DrawableHyperlinkCommandArchive",
    3041: "TSD_ConnectionLineConnectCommandArchive",
    3042: "TSD_InstantAlphaCommandArchive",
    3043: "TSD_DrawableLockCommandArchive",
    3045: "TSD_CanvasSelectionArchive",
    3046: "TSD_CommandSelectionBehaviorArchive",
    3047: "TSD_GuideStorageArchive",
    3048: "TSD_StyledInfoSetStyleCommandArchive",
    3049: "TSD_DrawableInfoCommentCommandArchive",
    3050: "TSD_GuideCommandArchive",
    3051: "TSD_DrawableAspectRatioLockedCommandArchive",
    3052: "TSD_ContainerRemoveChildrenCommandArchive",
    3053: "TSD_ContainerInsertChildrenCommandArchive",
    3054: "TSD_ContainerReorderChildrenCommandArchive",
    3055: "TSD_ImageAdjustmentsCommandArchive",
    3056: "TSD_CommentStorageArchive",
    3057: "TSD_ThemeReplaceFillPresetCommandArchive",
    3058: "TSD_DrawableAccessibilityDescriptionCommandArchive",
    3059: "TSD_PasteStyleCommandArchive",
    3060: "TSD_CommentStorageApplyCommandArchive",
    4000: "TSCE_CalculationEngineArchive",
    4001: "TSCE_FormulaRewriteCommandArchive",
    4002: "TSCE_TrackedReferencesRewriteCommandArchive",
    4003: "TSCE_NamedReferenceManagerArchive",
    4004: "TSCE_ReferenceTrackerArchive",
    4005: "TSCE_TrackedReferenceArchive",
    5000: "TSCH_PreUFF_ChartInfoArchive",
    5002: "TSCH_PreUFF_ChartGridArchive",
    5004: "TSCH_ChartMediatorArchive",
    5010: "TSCH_PreUFF_ChartStyleArchive",
    5011: "TSCH_PreUFF_ChartSeriesStyleArchive",
    5012: "TSCH_PreUFF_ChartAxisStyleArchive",
    5013: "TSCH_PreUFF_LegendStyleArchive",
    5014: "TSCH_PreUFF_ChartNonStyleArchive",
    5015: "TSCH_PreUFF_ChartSeriesNonStyleArchive",
    5016: "TSCH_PreUFF_ChartAxisNonStyleArchive",
    5017: "TSCH_PreUFF_LegendNonStyleArchive",
    5020: "TSCH_ChartStylePreset",
    5021: "TSCH_ChartDrawableArchive",
    5022: "TSCH_ChartStyleArchive",
    5023: "TSCH_ChartNonStyleArchive",
    5024: "TSCH_LegendStyleArchive",
    5025: "TSCH_LegendNonStyleArchive",
    5026: "TSCH_ChartAxisStyleArchive",
    5027: "TSCH_ChartAxisNonStyleArchive",
    5028: "TSCH_ChartSeriesStyleArchive",
    5029: "TSCH_ChartSeriesNonStyleArchive",
    5103: "TSCH_CommandSetChartTypeArchive",
    5104: "TSCH_CommandSetSeriesNameArchive",
    5105: "TSCH_CommandSetCategoryNameArchive",
    5107: "TSCH_CommandSetScatterFormatArchive",
    5108: "TSCH_CommandSetLegendFrameArchive",
    5109: "TSCH_CommandSetGridValueArchive",
    5110: "TSCH_CommandSetGridDirectionArchive",
    5113: "TSCH_SynchronousCommandArchive",
    5114: "TSCH_CommandReplaceAllArchive",
    5115: "TSCH_CommandAddGridRowsArchive",
    5116: "TSCH_CommandAddGridColumnsArchive",
    5117: "TSCH_CommandSetPreviewLocArchive",
    5118: "TSCH_CommandMoveGridRowsArchive",
    5119: "TSCH_CommandMoveGridColumnsArchive",
    5120: "TSCH_CommandDeleteGridRowsArchive",
    5121: "TSCH_CommandDeleteGridColumnsArchive",
    5122: "TSCH_CommandSetPieWedgeExplosion",
    5123: "TSCH_CommandStyleSwapArchive",
    5124: "TSCH_CommandChartApplyTheme",
    5125: "TSCH_CommandChartApplyPreset",
    5126: "TSCH_ChartCommandArchive",
    5127: "TSCH_CommandReplaceGridValuesArchive",
    5129: "TSCH_StylePasteboardDataArchive",
    5130: "TSCH_CommandSetMultiDataSetIndexArchive",
    5131: "TSCH_CommandReplaceThemePresetArchive",
    5132: "TSCH_CommandInvalidateWPCaches",
    6000: "TST_TableInfoArchive",
    6001: "TST_TableModelArchive",
    6002: "TST_Tile",
    6003: "TST_TableStyleArchive",
    6004: "TST_CellStyleArchive",
    6005: "TST_TableDataList",
    6006: "TST_HeaderStorageBucket",
    6007: "TST_WPTableInfoArchive",
    6008: "TST_TableStylePresetArchive",
    6009: "TST_TableStrokePresetArchive",
    6010: "TST_ConditionalStyleSetArchive",
    6100: "TST_TableCommandArchive",
    6101: "TST_CommandDeleteCellsArchive",
    6102: "TST_CommandInsertColumnsOrRowsArchive",
    6103: "TST_CommandRemoveColumnsOrRowsArchive",
    6104: "TST_CommandResizeColumnOrRowArchive",
    6105: "TST_CommandSetCellArchive",
    6106: "TST_CommandSetNumberOfHeadersOrFootersArchive",
    6107: "TST_CommandSetTableNameArchive",
    6108: "TST_CommandStyleCellsArchive",
    6109: "TST_CommandFillCellsArchive",
    6110: "TST_CommandReplaceAllTextArchive",
    6111: "TST_CommandChangeFreezeHeaderStateArchive",
    6112: "TST_CommandReplaceTextArchive",
    6113: "TST_CommandPasteArchive",
    6114: "TST_CommandSetTableNameEnabledArchive",
    6115: "TST_CommandMoveRowsArchive",
    6116: "TST_CommandMoveColumnsArchive",
    6117: "TST_CommandApplyTableStylePresetArchive",
    6118: "TST_CommandApplyStrokePresetArchive",
    6119: "TST_CommandSetExplicitFormatArchive",
    6120: "TST_CommandSetRepeatingHeaderEnabledArchive",
    6121: "TST_CommandApplyThemeToTableArchive",
    6122: "TST_CommandApplyThemeChildForTableArchive",
    6123: "TST_CommandSortArchive",
    6124: "TST_CommandToggleTextPropertyArchive",
    6125: "TST_CommandStyleTableArchive",
    6126: "TST_CommandSetNumberOfDecimalPlacesArchive",
    6127: "TST_CommandSetShowThousandsSeparatorArchive",
    6128: "TST_CommandSetNegativeNumberStyleArchive",
    6129: "TST_CommandSetFractionAccuracyArchive",
    6130: "TST_CommandSetSingleNumberFormatParameterArchive",
    6131: "TST_CommandSetCurrencyCodeArchive",
    6132: "TST_CommandSetUseAccountingStyleArchive",
    6134: "TST_CommandRewriteFormulasForSortArchive",
    6135: "TST_CommandRewriteFormulasForTectonicShiftArchive",
    6136: "TST_CommandSetTableFontNameArchive",
    6137: "TST_CommandSetTableFontSizeArchive",
    6138: "TST_CommandRewriteFormulasForMoveArchive",
    6139: "TST_CommandFixStylesInHeadersOrFootersArchive",
    6141: "TST_CommandResetFillPropertyToDefault",
    6142: "TST_CommandSetTableNameHeightArchive",
    6143: "TST_CommandMergeUnmergeArchive",
    6144: "TST_MergeRegionMapArchive",
    6145: "TST_CommandHideShowArchive",
    6146: "TST_CommandSetBaseArchive",
    6147: "TST_CommandSetBasePlacesArchive",
    6148: "TST_CommandSetBaseUseMinusSignArchive",
    6179: "TST_FormulaEqualsTokenAttachmentArchive",
    6181: "TST_TokenAttachmentArchive",
    6182: "TST_ExpressionNodeArchive",
    6183: "TST_BooleanNodeArchive",
    6184: "TST_NumberNodeArchive",
    6185: "TST_StringNodeArchive",
    6186: "TST_ArrayNodeArchive",
    6187: "TST_ListNodeArchive",
    6188: "TST_OperatorNodeArchive",
    6189: "TST_FunctionNodeArchive",
    6190: "TST_DateNodeArchive",
    6191: "TST_ReferenceNodeArchive",
    6192: "TST_DurationNodeArchive",
    6193: "TST_ArgumentPlaceholderNodeArchive",
    6194: "TST_PostfixOperatorNodeArchive",
    6195: "TST_PrefixOperatorNodeArchive",
    6196: "TST_FunctionEndNodeArchive",
    6197: "TST_EmptyExpressionNodeArchive",
    6198: "TST_LayoutHintArchive",
    6199: "TST_CompletionTokenAttachmentArchive",
    6200: "TST_FormulaEditingCommandGroupArchive",
    6201: "TST_TableDataList",
    6202: "TST_CommandCoerceMultipleCellsArchive",
    6203: "TST_CommandSetMultipleCellsCustomArchive",
    6204: "TST_HiddenStateFormulaOwnerArchive",
    6205: "TST_CommandSetAutomaticDurationUnitsArchive",
    6206: "TST_PopUpMenuModel",
    6207: "TST_CommandSetControlMinimumArchive",
    6208: "TST_CommandSetControlMaximumArchive",
    6209: "TST_CommandSetControlIncrementArchive",
    6210: "TST_CommandSetControlCellsDisplayNumberFormatArchive",
    6211: "TST_CommandSetMultipleCellsMultipleChoiceListArchive",
    6212: "TST_CommandSetMultipleChoiceListFormatForEditedItemArchive",
    6213: "TST_CommandSetMultipleChoiceListFormatForDeleteItemArchive",
    6214: "TST_CommandSetMultipleChoiceListFormatForReorderItemArchive",
    6215: "TST_CommandSetMultipleChoiceListFormatForInitialValueArchive",
    6216: "TST_CommandRewriteFormulasForCellMergeArchive",
    6217: "TST_TableInfoGeometryCommandArchive",
    6218: "TST_RichTextPayloadArchive",
    6219: "TST_EditingStateArchive",
    6220: "TST_FilterSetArchive",
    6221: "TST_CommandSetFiltersEnabledArchive",
    6222: "TST_CommandRewriteFilterFormulasForTectonicShiftArchive",
    6223: "TST_CommandRewriteFilterFormulasForSortArchive",
    6224: "TST_CommandRewriteFilterFormulasForTableResizeArchive",
    6225: "TST_CommandSetAutomaticFormatArchive",
    6226: "TST_CommandTextPreflightInsertCellArchive",
    6227: "TST_FormulaEditingCommandSelectionBehaviorArchive",
    6228: "TST_CommandDeleteCellContentsArchive",
    6229: "TST_CommandPostflightSetCellArchive",
    6231: "TST_CommandRewriteConditionalStylesForTectonicShiftArchive",
    6232: "TST_CommandRewriteConditionalStylesForSortArchive",
    6233: "TST_CommandRewriteConditionalStylesForRangeMoveArchive",
    6234: "TST_CommandRewriteConditionalStylesForCellMergeArchive",
    6235: "TST_IdentifierNodeArchive",
    6236: "TST_UndoRedoStateCommandSelectionBehaviorArchive",
    6237: "TST_CommandSetStyleApplyClearsAllFlagArchive",
    6238: "TST_CommandSetDateTimeFormatArchive",
    6239: "TST_TableCommandSelectionBehaviorArchive",
    6240: "TST_CommandAddQuickFilterRulesArchive",
    6241: "TST_CommandModifyFilterRuleArchive",
    6242: "TST_CommandDeleteFilterRulesArchive",
    6244: "TST_CommandApplyCellCommentArchive",
    6245: "TST_CommandApplyConditionalStyleSetArchive",
    6246: "TST_CommandSetFormulaTokenizationArchive",
    6247: "TST_TableStyleNetworkArchive",
    6248: "TST_CommandSetFilterEnabledArchive",
    6249: "TST_CommandSetFilterRuleEnabledArchive",
    6250: "TST_CommandSetFilterSetTypeArchive",
    6251: "TST_CommandSetStyleNetworkArchive",
    6252: "TST_CommandMutateCellsArchive",
    6253: "TST_DisableTableNameSelectionBehaviorArchive",
    6254: "TST_CommandDisableFilterRulesForColumnArchive",
    6255: "TST_CommandSetTextStyleArchive",
    6256: "TST_CommandNotifyForTransformingArchive",
    11000: "TSP_PasteboardObject",
    11006: "TSP_PackageMetadata",
    11007: "TSP_PasteboardMetadata",
    11008: "TSP_ObjectContainer",
 } 
