class Keynote(object):
  KN_DocumentArchive= 1
  KN_ShowArchive= 2
  KN_UIStateArchive= 3
  KN_SlideNodeArchive= 4
  KN_SlideArchive= 5
  KN_SlideArchive= 6
  KN_PlaceholderArchive= 7
  KN_BuildArchive= 8
  KN_SlideStyleArchive= 9
  KN_ThemeArchive= 10
  KN_PasteboardNativeStorageArchive= 11
  KN_PlaceholderArchive= 12
  TSWP_TextualAttachmentArchive= 14
  KN_NoteArchive= 15
  KN_RecordingArchive= 16
  KN_RecordingEventTrackArchive= 17
  KN_RecordingMovieTrackArchive= 18
  KN_ClassicStylesheetRecordArchive= 19
  KN_ClassicThemeRecordArchive= 20
  KN_Soundtrack= 21
  KN_SlideNumberAttachmentArchive= 22
  KN_DesktopUILayoutArchive= 23
  KN_CanvasSelectionArchive= 24
  KN_SlideCollectionSelectionArchive= 25
  KN_CommandBuildSetValueArchive= 100
  KN_CommandShowInsertSlideArchive= 101
  KN_CommandShowMoveSlideArchive= 102
  KN_CommandShowRemoveSlideArchive= 103
  KN_CommandSlideInsertDrawablesArchive= 104
  KN_CommandSlideRemoveDrawableArchive= 105
  KN_CommandSlideNodeSetPropertyArchive= 106
  KN_CommandSlideInsertBuildArchive= 107
  KN_CommandSlideMoveBuildWithoutMovingChunksArchive= 108
  KN_CommandSlideRemoveBuildArchive= 109
  KN_CommandSlideInsertBuildChunkArchive= 110
  KN_CommandSlideMoveBuildChunkArchive= 111
  KN_CommandSlideRemoveBuildChunkArchive= 112
  KN_CommandSlideSetValueArchive= 113
  KN_CommandTransitionSetValueArchive= 114
  KN_UIStateCommandGroupArchive= 115
  KN_CommandSlidePasteDrawablesArchive= 116
  KN_CommandSlideApplyThemeArchive= 117
  KN_CommandSlideMoveDrawableZOrderArchive= 118
  KN_CommandChangeMasterSlideArchive= 119
  KN_CommandShowSetSlideNumberVisibilityArchive= 123
  KN_CommandShowSetValueArchive= 124
  KN_CommandShowMarkOutOfSyncRecordingArchive= 128
  KN_CommandShowRemoveRecordingArchive= 129
  KN_CommandShowReplaceRecordingArchive= 130
  KN_CommandShowSetSoundtrack= 131
  KN_CommandSoundtrackSetValue= 132
  KN_CommandMasterRescaleArchive= 133
  KN_CommandMoveMastersArchive= 134
  KN_CommandInsertMasterArchive= 135
  KN_CommandSlideSetStyleArchive= 136
  KN_CommandSlideSetPlaceholdersForTagsArchive= 137
  KN_CommandBuildChunkSetValueArchive= 138
  KN_CommandSlideMoveBuildChunksArchive= 139
  KN_CommandRemoveMasterArchive= 140
  KN_CommandRenameMasterArchive= 141
  KN_CommandMasterSetThumbnailTextArchive= 142
  KN_CommandShowChangeThemeArchive= 143
  KN_CommandSlidePrimitiveSetMasterArchive= 144
  KN_CommandMasterSetBodyStylesArchive= 145
  KN_CommandSlideReapplyMasterArchive= 146
  KN_SlideCollectionCommandSelectionBehaviorArchive= 147
  KN_ChartInfoGeometryCommandArchive= 148
  TSWP_SectionPlaceholderArchive= 10011


  DICTIONARY = {
    1: "KN_DocumentArchive",
    2: "KN_ShowArchive",
    3: "KN_UIStateArchive",
    4: "KN_SlideNodeArchive",
    5: "KN_SlideArchive",
    6: "KN_SlideArchive",
    7: "KN_PlaceholderArchive",
    8: "KN_BuildArchive",
    9: "KN_SlideStyleArchive",
    10: "KN_ThemeArchive",
    11: "KN_PasteboardNativeStorageArchive",
    12: "KN_PlaceholderArchive",
    14: "TSWP_TextualAttachmentArchive",
    15: "KN_NoteArchive",
    16: "KN_RecordingArchive",
    17: "KN_RecordingEventTrackArchive",
    18: "KN_RecordingMovieTrackArchive",
    19: "KN_ClassicStylesheetRecordArchive",
    20: "KN_ClassicThemeRecordArchive",
    21: "KN_Soundtrack",
    22: "KN_SlideNumberAttachmentArchive",
    23: "KN_DesktopUILayoutArchive",
    24: "KN_CanvasSelectionArchive",
    25: "KN_SlideCollectionSelectionArchive",
    100: "KN_CommandBuildSetValueArchive",
    101: "KN_CommandShowInsertSlideArchive",
    102: "KN_CommandShowMoveSlideArchive",
    103: "KN_CommandShowRemoveSlideArchive",
    104: "KN_CommandSlideInsertDrawablesArchive",
    105: "KN_CommandSlideRemoveDrawableArchive",
    106: "KN_CommandSlideNodeSetPropertyArchive",
    107: "KN_CommandSlideInsertBuildArchive",
    108: "KN_CommandSlideMoveBuildWithoutMovingChunksArchive",
    109: "KN_CommandSlideRemoveBuildArchive",
    110: "KN_CommandSlideInsertBuildChunkArchive",
    111: "KN_CommandSlideMoveBuildChunkArchive",
    112: "KN_CommandSlideRemoveBuildChunkArchive",
    113: "KN_CommandSlideSetValueArchive",
    114: "KN_CommandTransitionSetValueArchive",
    115: "KN_UIStateCommandGroupArchive",
    116: "KN_CommandSlidePasteDrawablesArchive",
    117: "KN_CommandSlideApplyThemeArchive",
    118: "KN_CommandSlideMoveDrawableZOrderArchive",
    119: "KN_CommandChangeMasterSlideArchive",
    123: "KN_CommandShowSetSlideNumberVisibilityArchive",
    124: "KN_CommandShowSetValueArchive",
    128: "KN_CommandShowMarkOutOfSyncRecordingArchive",
    129: "KN_CommandShowRemoveRecordingArchive",
    130: "KN_CommandShowReplaceRecordingArchive",
    131: "KN_CommandShowSetSoundtrack",
    132: "KN_CommandSoundtrackSetValue",
    133: "KN_CommandMasterRescaleArchive",
    134: "KN_CommandMoveMastersArchive",
    135: "KN_CommandInsertMasterArchive",
    136: "KN_CommandSlideSetStyleArchive",
    137: "KN_CommandSlideSetPlaceholdersForTagsArchive",
    138: "KN_CommandBuildChunkSetValueArchive",
    139: "KN_CommandSlideMoveBuildChunksArchive",
    140: "KN_CommandRemoveMasterArchive",
    141: "KN_CommandRenameMasterArchive",
    142: "KN_CommandMasterSetThumbnailTextArchive",
    143: "KN_CommandShowChangeThemeArchive",
    144: "KN_CommandSlidePrimitiveSetMasterArchive",
    145: "KN_CommandMasterSetBodyStylesArchive",
    146: "KN_CommandSlideReapplyMasterArchive",
    147: "KN_SlideCollectionCommandSelectionBehaviorArchive",
    148: "KN_ChartInfoGeometryCommandArchive",
    10011: "TSWP_SectionPlaceholderArchive",
 } 
